name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  camera_platform_interface:
    path: ../../camera_platform_interface
  camera_windows:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
dependency_overrides:
   {camera_platform_interface: {path: ../../../camera/camera_platform_interface}, camera_windows: {path: ../../../camera/camera_windows}}
