name: camera_windows_example
description: Demonstrates how to use the camera_windows plugin.
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  camera_platform_interface: ^2.6.0
  camera_windows:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
