name: camera_android_camerax_example
description: Demonstrates how to use the camera_android_camerax plugin.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera_android_camerax:
    path: ../
  camera_platform_interface:
    path: ../../camera_platform_interface

  flutter:
    sdk: flutter
  video_player: ^2.4.10

dev_dependencies:
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
dependency_overrides:
   {camera_android_camerax: {path: ../../../camera/camera_android_camerax}, camera_platform_interface: {path: ../../../camera/camera_platform_interface}}
